### ISSUE TITLE
docker domain name

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#23]
nginx-proxy:
https://github.com/i3thuan5/hok8-bu7/blob/master/docker-compose.yml#L13-L20
```
   networks:
      - default
      - nginx-bridge
    expose:
      - 8000
    environment:
      VIRTUAL_HOST: "xn--lhrz38b.xn--v0qr21b.xn--kpry57d"
VIRTUAL_PORT: 8000
```

https://github.com/i3thuan5/hok8-bu7/blob/master/docker-compose.yml#L36-L39
```
networks:
  nginx-bridge:
    external: true
```
